### ISSUE TITLE
Looking for documentation about XsdGroup, XsdComplexType, NamespaceView...

### ISSUE THREAD

**Issue by arkceajin** [sissaschool/xmlschema#124]
Cannot find the documentation about the XsdGroup, XsdComplexType, NamespaceView... classes in https://xmlschema.readthedocs.io.

**Comment by arkceajin** [comment]
my bad loaded the wrong xsd...

**Comment by brunato** [comment]
Hi,
some components are internals (eg. *NamespaceView*) so I won't to publish information about them because they may change without forewarning.
Anyway for schema components (*XsdComponent* and subclasses) I had thought to publish something after the completion of XSD 1.1 development. In this case it will be marked explicitly as unstable API or include only the subset of method/properties/attributes that are considered stable.

**Comment by brunato** [comment]
Added XSD components in documentation for whatever is considered stable.
