### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by msenra** [sissaschool/xmlschema#138]
I am testing the new version and as for small files, no problem, with the large still could not validate any.
So,
What is the exact syntax for using the 'lazy' and 'lax' or 'strict' mode parameters.
By the way what is the best way to validate a file with a size of 129Mb. (schema 1.1)

Thanks.

**Comment by brunato** [comment]
Hi,

the *lazy* argument is related on how the XMLResource, created from *source/xml_document* argument, is loaded into memory. With *lazy* mode the XML document is not loaded entirely into memory (with `ElementTree.parse`) but is iterated with `ElementTree.iterparse` and the processed branches are deleted ASAP to save memory. This feature is available only for package API and is still *experimental*. Currently it's still very slow but maybe improved in the next release (see my last comment on issue #102) because the XMLResource class will be updated (PR #122).

'lax' and 'strict' are validation modes (the other is 'skip' that has sense only if you need only a decoding), regulated with *validation* argument. Have you read about this on the available [xmlschema's documentation](https://xmlschema.readthedocs.io/en/latest/index.html)?

**Comment by msenra** [comment]
Hi, sorry for my misunderstanding about the parameters and validation mode, but my english is very basic and there must have been any bad translations.
Still, the question remains: is it possible to validate a 129mb xml file with a v1.1 schema? If so what is the best way.

Python 3.7.4
i5
Windows 10
8 GB Ram

I appreciate the patience,
Thanks.

**Comment by brunato** [comment]
The answer is *yes*, but don't use *lazy* mode until the next release because the it's too slow at the moment. In the normal mode the memory consumption will be around 2-3 times the XML file size.
For validation use the functions `xmlschema.validate`.

Probably a new release will be available in about a week because I've to fix a bug that affects XSD wildcards components.

**Comment by msenra** [comment]
Hi, sorry to bother you again.
I was testing with the latest version and could not validate a file with 128mb. The validator ran for 14 hours and did not finish. It must be because it is very large, because small files it finishes the validation.
I send you the test files if you want to test.
Thanks.
[TestFiles.zip](https://github.com/sissaschool/xmlschema/files/3738096/TestFiles.zip)

**Comment by brunato** [comment]
Ok, I will try to verify where can be the problem ...

**Comment by msenra** [comment]
News?

**Comment by brunato** [comment]
Hi,

it stalls also for me (tested with release v1.0.16). This happens also if I use also the *decode* API instead of *validate* API.

Instead it works pretty well with `path="*"` or *lazy* validation mode (that works inserting `path="*"`):

```python
>>> from datetime import datetime as dt
>>> import xmlschema
>>> xs = xmlschema.XMLSchema11("fXsd.xsd")
>>> print(dt.now()); xmlschema.validate("fXml.xml", schema=xs, path="*"); print(dt.now())
2019-11-18 12:53:03.891515
2019-11-18 12:56:19.168121
>>> print(dt.now()); xmlschema.validate("fXml.xml", schema=xs, lazy=True); print(dt.now())
2019-11-18 12:59:10.093208
2019-11-18 13:02:30.650529
```
I think this can be related to a very big result dict, that is produced in case of a big file with the default mode. This needs a custom deeper inspection to verify if it's can be resolved. In any case for big files I suggest to use lazy mode with the `xmlschema.validation` API.

**Comment by msenra** [comment]
Hi,
First of all, congratulations on this great work. 
In my case and since I just need to validate it seems to me that it works well (I keep testing).
Is there a way to validate the entire document and not exit after the first error? (in the end list all errors)

Thank you anyway.

**Comment by brunato** [comment]
To obtain all errors build the schema and then use schema.iter_errors() API. This is a generator, so you can print (or collect) each error and continue for the next until the stop of iteration. To use this API in lazy mode at the moment you need to build an `XMLResource`, eg.:

```python
from xmlschema import XMLResource
source = XMLResource(xml_file_path, lazy=True)
for error in self.iter_errors(source, lazy=True):
    print(error)
```
Bye

**Comment by msenra** [comment]
Thank you again,

Sorry but I don't have enough knowledge to do what you suggest.
Could you be a little more specific, please?

**Comment by brunato** [comment]
I've updated the previous code with a complete recipe. I the next release I will extend *lazy mode* also to schema-level API (*iter_errors()* included...) in order to simplify their usage in similar cases.
Cheers

**Comment by msenra** [comment]
Sorry, but I still don't understand where to put this function and where to call it and how to call it.

thanks.

**Comment by brunato** [comment]
Ok, I close the issue but I consider that for next releases API and documentation.
Bye
