### ISSUE TITLE
The package is imposibly slow with PyPy

### ISSUE THREAD

**Issue by mgorny** [sissaschool/xmlschema#146]
Running the tests on PyPy is much slower than on CPython. While *some* slowdown might be expected (due to startup overhead), we're talking about 70x slower here. For example, runtimes with prepopulated tox envs:

```
$ time tox -e py27
[...]
real    0m55.912s
user    0m49.310s
sys     0m1.151s
$ time tox -e pypy
[...]
real    63m4.431s
user    62m55.030s
sys     0m1.873s
```

**Comment by mgorny** [comment]
(note: I had to add pathlib2 for pypy in tox.ini)

**Comment by brunato** [comment]
Hi,
this library is not for PyPy yet. I think the slowness can be due to the generation of decoded data during the validation process. But with PyPy-3 is bad but not so bad (a test in a venv):

```
# time python xmlschema/tests/test_all.py
Ran 464 tests in 60.451s

FAILED (failures=3, skipped=6)

real	1m3.187s
user	0m55.896s
sys	0m0.561s
```

The Python 2.7 support will be dropped soon (probably the next release v1.0.17 going to be the last version compatible with 2.7). After that maybe a testing with PyPy3 could be deepen.

**Comment by brunato** [comment]
Hi @mgorny,
I've published the first Python 3-only release. The run of the package's tests with PyPy3 (PyPy 7.1.1-beta0) against Python 3.8, PyPy is 2-3 times slower, but with validation of big files (my test file is about 45MB ...) PyPy is about 1.6x faster that Python 3.8 and 2.5x faster in validation of further files in the same process. Not so much but enough to close this issue.

Note: Testing and support of PyPy3 will be probably included in the next release.
