### ISSUE TITLE
General XML compliance error and Jython Support

### ISSUE THREAD

**Issue by ArnoCan** [sissaschool/xmlschema#150]
Hello,
I have tried to use xmlschema for a platform with support for various Python implementations an failed first on Jython. The cause was a common error in the compliance to the XML standards.
Jython ignores the non-available surrogates, e.g. 0xD000-0xDFFF. These are not permitted by XML, and so by XSLT anyway. Thus raises an exception.

Now the long part, In order to find the bug I had to do a number of changes and patches which I have described in a document. This mainly includes the reorganization of the test cases in order to fit better into PyDev/Eclipse. I also patched the code appropriately for Jython. The code base is of 2019.05.16.

The document and the patches are available at:
- https://xmlschema-acue.sourceforge.io/index.html
- https://github.com/ArnoCan/xmlschema_acue

WKR

**Comment by ArnoCan** [comment]
The code base I have used is:

- https://github.com/ArnoCan/xmlschema-org

WKR

**Comment by brunato** [comment]
Hi,
congratulation for the huge work for extending XML Schema on other Python implementations. About the XML compliance I mainly had the target to focusing on XSD, taking what CPython provides and support, and also the limitations. This because this is the currently needs of the scientific people that I work with (mainly scientits that develop with Fortran). 

My roadmap is to migrate the code to support only Python 3 and then completing W3C XML tests coverage (about 1% still failing ...) and try to extend support to PyPy and also Cython (using also type annotations). For version v1.1 I had already the idea to moving out tests code from the package code, putting it in a tests/ directory. Test code will remain based on *unittest* and the W3C conformance tests will remain still optionals.
