### ISSUE TITLE
XsdSimpleType is_emptiable is not enough

### ISSUE THREAD

**Issue by bdauvergne** [sissaschool/xmlschema#152]
I make this remark not knowing exactly the expected semantic of is_emptiable, but we have the following need : we produce JSON schema corresponding to the conversion of XML documents to JSON using xmlschema with UnorderdConverter (you can see the code there http://git.entrouvert.org/passerelle.git/tree/passerelle/utils/xml.py#n114, it's a work in progress, we do not have full support for XSchema for now, only the XSD files we really use).

We noticed the following facts:
* if an element simpleType has in its lexical space the empty-string i.e. given by an XML structure like `<A/>` or `<A></A>`, xmlschema will produce `{'A': null}` or `{'A': [null]}` if `maxOccurs > 1`.
* at the JSON schema level we would like to describe it by `json-schema(simple-type)` or `{'oneOf': [json-schema(simple-type), {'type': 'null'}]}` (the later case for the case where the lexical space accept the empty-string or empty-node).
* we thought we could use XsdSimpleType.is_emptiable() but it just verifies that self.min_length == 0 which is not precise enough, if the simple-type is a enumeration of non empty-string then is_emptiable() should be false (or if there is some patterns restrictions which does not accept the empty-string also)

My question is : would a new implementation of is_emptiable() which would recursively iterate on patterns and validators to really check for the possibilité of an empty string would be an acceptable new behaviour for XsdSimpleType.is_emptiable() ? 

The new behaviour would certainly be implemented on the subclasses like XsdUnion and XsdAtomicRestriction, for builtin the status of is_emptiable() should be determined by the XSchema specification.

**Comment by brunato** [comment]
Hi,

thank you for the analisys. After some tests I think that is possible (auspicable) to change *is_emptiable()* to take count for these cases where there are patterns or enumerations.

For making this I will add an attribute *allow_empty* that is `True` for default and is changed to `False` during XSD parsing phase if one of these conditions happen:
- `min_length > 0`
- there are patterns and empty sting is not matched
- there are enumerations and the empty string is not included

For *XsdUnion* and *XsdList* the rule for setting this attribute to `False` will be different (based only for members for XsdUnion and based on item type and *min_length* for XsdList).

These modifications don't affect the validity of my tests (also W3C 15000+ schema tests).

So after then you can still continue to use is_emptiable() (a general call for all XSD types) or check *allow_empty* attribute (only for simple types).
 
It would be enough for your needs or there is somenthing that I've not considered?

P.S.: I'm happy to see that *xmlschema* is used in couple with *jsonschema* for making your project, because the other package is the one that that I've taken inspiration from in 2016, after following a presentation by the author of *jsonschema* at the italian PyCon conference.

Thanks
Davide

**Comment by bdauvergne** [comment]
> It would be enough for your needs or there is something that I've not considered?
It seems perfect for me, and thank you for xmlschema, I initially intended to use the XSchema support inside zeep but it was too difficult.

**Comment by brunato** [comment]
The new behaviour for *XsdSimpleType.is_emptiable()* is available with v1.0.17+.
Bye

**Comment by bdauvergne** [comment]
Thanks.
