### ISSUE TITLE
cant access elements outside default namespace or xsd namespaces referenced on the web

### ISSUE THREAD

**Issue by Hazedd** [sissaschool/xmlschema#158]
Hi,

i have a complex set of xsd documents with multiple namespaces. I want to make a documentation json that gives me all info of object to create a form. 

i know the goal is outside the scope of xmlschema but i gave it a shot and im allmost there. see below for a example of the output json.

```
{
	"object_type": "Signal",
	"documentation": "Een lichtsein is een variabel sein waarvan de beelden door lichten (rood, geel of groen), al dan niet knipperend, worden getoond.",
	"attributes": [
		{........,
		{
			"name": "hasWhitebarETCSIndicator",
			"documentation": "Indicatie of sein is voorzien van een lichtbak ten behoeve ERTMS. Als deze brandt werkt ERTMS als beveiliging.",
			"usage": "required",
			"type": "tTrueFalseEnum",
			"root_type": "string",
			"facets": {
				"enumeration": [
					"Unknown",
					"True",
					"False"
				],
				"whiteSpace": "preserve"
			}
		}
	],
	"elements": [
		{ ...........,
		{
			"name": "IlluminatedSign",
			"documentation": null,
			"min_occurs": 0,
			"max_occurs": null,
			"attributes": [
				{
					"name": "puic",
					"documentation": "UUID om het object gedurende de levensduur te kunnen identificeren en om naar te refereren.",
					"usage": "required",
					"type": "tUUID",
					"root_type": "string",
					"facets": {
						"length": "36",
						"pattern": "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[8-9a-bA-B][0-9a-fA-F]{3}-[0-9a-fA-F]{12}",
						"whiteSpace": "preserve"
					}
				},
				........
			],
			"elements": [
				{
					"name": "Metadata",
					"documentation": null,
					"min_occurs": 0,
					"max_occurs": 1,
					"attributes": [
						{
							"name": "originType",
							"documentation": "Geeft aan voor gemeenschappelijke objecttypes  of het object alleen in BBK, alleen in IA of in allebei voorkwam",
							"usage": "required",
							"type": "tSourceOriginEnum",
							"root_type": "string",
							"facets": {
								"enumeration": [
									"Unknown",
									"IA",
									"BBK",
									"SharedMatched",
									"SharedIAOnly",
									"SharedBBKOnly",
									"GEOPOORT",
									"SharedGEOPOORTOnly",
									"Other"
								],
								"whiteSpace": "preserve"
							}
						},
```

One of the xsd's is targeting a gml xsd to make some custom changes 

sample of the custom gml xsd:
```
<xs:schema xmlns="http://www.opengis.net/gml" xmlns:gml="http://www.opengis.net/gml" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.opengis.net/gml" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Point">
		<xs:annotation>
			<xs:documentation>Een punt in RD-coordinaten</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="gml:coordinates"/>
			</xs:sequence>
			<xs:attribute name="srsName" type="xs:anyURI">
				<xs:annotation>
					<xs:documentation>Het gewenste coordinatenstelsel</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
```

i have created a schema from the xsd that includes all other xsd's. for the elements in the default namespace i can get them by name. the elements outside the default namespace i cant get by name.

```
my_schema.elements.get("FlankProtectionConfiguration")
XsdElement(name='FlankProtectionConfiguration', occurs=[1, 1])
my_schema.elements.get("Point")
None
```

in debug mode i can see the xsd elements from all local xsd files in the the schema object created by xmlschema, just not the xsd referenced online.

sample of the schema.maps.elements
```
'{http://www.prorail.nl/IMSpoor}FlankProtectionConfiguration'
'{http://www.opengis.net/gml}Point'
```

****how do i get those gml elements as a XsdElement object? ****

thx inadvanced!

**Comment by brunato** [comment]
Hi,
the elements accessible at schema level (eg. *my_schema.elements*) are a view of the elements of the namespace (targetNamespace) of the schema. At this level the namespace is stripped for simplicity but the object is the same XsdElement that you can find in *my_schema.maps.elements*, referrable with full qualified name.

The `'{http://www.opengis.net/gml}Point'` element is located in a schema related to the gml namespace, that can be found in `my_schema.maps.namespaces['http://www.opengis.net/gml']` (a list containing all the schema resources loaded for gml namespace). But as I see your additional schema for gml is not loaded, probably because when a namespace is imported no other resource is loadable for the same namespace (except with an include statement). This is the standard behaviour. Usually a redefine or override is used in these cases to modify the original definitions of the namespace.

In your case to let the additional element `'{http://www.opengis.net/gml}Point'` defined you have to modify your index xsd to import gml namespace from the local file where Point is defined and add an include statement into your gml additional file.

I hope this can be helpful for you.

**Comment by Hazedd** [comment]
Will Try some stuff next week👍
