### ISSUE TITLE
Dump a schema to JSON schema ?

### ISSUE THREAD

**Issue by eLvErDe** [sissaschool/xmlschema#163]
Hello,

My goal is to create [OpenAPI](https://swagger.io/specification/) definitions from elements on a huge XDS file.
Is that something I could do with your module ? I'm pretty sure it's should be doable, as you're already doing XML-JSON and JSON-XML, I'm just struggling figuring out to start.
I known this is not really an issue but we could consider this as a feature request ;-)

Thanks in advance,

Best regards, Adam.

**Comment by brunato** [comment]
Hi,
converting instances is pretty different than converting schemas and the latter is not a goal of this library. But someone is already using xmlschema internal API for trying to build schema translators (see issue #152) and my support on this is to provide step-by-step a more reliable internal API, in particular for XSD types.

Anyway I think that a general XSD-JSONSchema conversion is not a simple task because the two standards are pretty different.

Also I knew OpenAPI has still to decide to continue to support it's own json schema variant or to align to the latest version of JSON schema draft (for my experience the second should be a more better choice).  Furthersome, after this decision, the OpenAPI community should going to discuss the opportunity to introduce alternative schema for different schema types.

**Comment by brunato** [comment]
Hi @eLvErDe,

closing this issue I want to inform you that I've received the request to develop a new package for building XSD-compliant data structures. This new package will be based on xmlschema and jinja2 templates. Current needs are for producing C, Fortran and Python code, but it could be consequential to experiment the also JSON schemas generation.

Best regards
