### ISSUE TITLE
Values of an extension type derived from an empty base type are wrapped in a list

### ISSUE THREAD

**Issue by danifus** [sissaschool/xmlschema#165]
The first commit with this behaviour was b0cac58b5

I've prepared a branch with a failing test: https://github.com/danifus/xmlschema/tree/b165

This is due to `self` evaluating Falsey in `ModelGroup.is_single()` being called here: https://github.com/sissaschool/xmlschema/blob/6b2db69cec7425da8699d93e909cdd60ead29b4a/xmlschema/converters.py#L262

The base type is used for the `is_single()` call which returns False because the base type has no elements. The extended type should be used instead.

It might also be a problem at the following site too, but I didn't check.

https://github.com/sissaschool/xmlschema/blob/6b2db69cec7425da8699d93e909cdd60ead29b4a/xmlschema/converters.py#L605

**Comment by brunato** [comment]
Hi,
for groups there is the need of a more specific version of *is_single()*, because a group can be composed of nested groups with different values of max_occurs. The new method:

```python
def is_single(self):
    if self.max_occurs != 1 or not self:
        return False
    elif len(self) > 1:
        return True
    else:
        return self[0].is_single()
```
checks the internal structure of the group, not the base type. It maybe fails on some pathological cases or the empty groups have to be categorized as non-single. 
Could you report me about the structure of this group that fails?

Thank you

**Comment by danifus** [comment]
Thanks for looking into it.

The test case I supplied in the linked branch has a simplified case of the behaviour I'm experiencing. I think it has to do with specifying a type by `xsi:type="..."`.

https://github.com/danifus/xmlschema/blob/01465a3ac056268a8ce47404c2313be57f42d537/tests/validation/test_decoding.py#L786-L830

Thanks,
Dan

**Comment by brunato** [comment]
> I think it has to do with specifying a type by `xsi:type="..."`.

I think so too.
The most reasonable remedy maybe to add an optional argument xsd_type to methods *element_decode* of converter classes, eg:

```python
    def element_decode(self, data, xsd_element, xsd_type=None, level=0):
        xsd_type = xsd_type or xsd_element.type
        # ....
```
All the references *xsd_element.type* in code have to be substituted by *xsd_type*.

For *element_encode* methods this cannot be done, because the type can be checked only after data shaping. But at first sight this will not be a problem, because these methods already count on the shape of input data and for limitations on variance of xsi:type or XSD 1.1 type alternatives substitutions.

Do you mind if I reuse your new test or do you prefer to make a PR for this adding also changes on *element_decode* methods?

Thank you

**Comment by danifus** [comment]
I've created a pull request or you can add it in directly. Which ever is easiest for you :)

**Comment by brunato** [comment]
Okay, we will update after fixes on *element_decode* methods and a new release.
Bye
