### ISSUE TITLE
Module loading is slow

### ISSUE THREAD

**Issue by plexilcrf** [sissaschool/xmlschema#205]
First off, thank you for this module. It is the first XML Schema 1.1 validator I have found that I can actually get to run.

I've written a simple Python script around this module, and use it for testing XSLT and compiler output. It seems a fair bit slower to start up than xmllint, which I was using before.

I measured module loading time in a virtual environment on macOS 10.15.7 with python3 3.8.5 from Homebrew. 'python -X importtime validate-plexil.py --help' generated the attached profile. Module loading time seems dominated by xmlschema.validators.identities, with significant contributions from xmlschema.validators.schema, elementpath.xpath2.xpath2_constructors, and xmlschema.validators.facets.

I was able to cut schema loading time by pickling the schema on first successful load, and loading the cached version on subsequent runs. I wonder if a similar approach would work here?

[xmlschema-import-profile.txt](https://github.com/sissaschool/xmlschema/files/5356455/xmlschema-import-profile.txt)

[validate-plexil.py.txt](https://github.com/sissaschool/xmlschema/files/5356460/validate-plexil.py.txt)

**Comment by brunato** [comment]
Hi,

thank you for reporting me you observations on speed. The approach of this library is to build XSD 1.0/1.1 meta-schemas and use them to validate other schemas before the parsing phase. This is flexible and simplify the parsing checks. 

The build of XSD meta-schemas is lazy so XSD 1.1 meta-schema is built at first usage of XMLSchema11 class. The most slower parts on checking schemas are surely identities checks.
For elementpath the XPath2 contructors module takes the longest time to load because it's the ending module of the XPath 2 parser, that ends with a build of the tokenizer. I will check if some parts of the parser building process can be accomplished faster.

Pickling surely can be used to improve building speed. A serialized schema also includes a build of the meta-schema. I will examine if pickling can also be used for caching the meta-schema in a transparent manner.

**Comment by brunato** [comment]
Checking with `python -X importtime -c 'import xmlschema'` i found that the high loading time of module *xmlschema.validators.identities* is due to re.compile() calls. In fact, moving these calls into another module the result dramatically change:

```
import time:    132259 |     132259 |         xmlschema.validators.patterns
import time:      3223 |     154829 |       xmlschema.validators.identities
```

The major impact is from XML Schema translated regex patterns, used for checking XPath expressions of _xs:selector_ and _xs:field_. For these, using a LazyPattern wrapper class the import time can be reduced:

```
import time:      1333 |       1333 |         xmlschema.validators.patterns
import time:      8746 |      29609 |       xmlschema.validators.identities
```

But this time is transferred to a longer meta-schema building time. Using a simple script ([timing-meta-pickle.zip](https://github.com/sissaschool/xmlschema/files/5464626/timing-meta-pickle.zip))
for check the differences between building or pickling the meta-schema the results:

```
*** Timing building VS pickling meta-schema ***

Build XSD 1.0 meta-schema: 0.1868 s
Build XSD 1.1 meta-schema: 0.0598 s
Pickle XSD 1.0 meta-schema: 0.0332 s
Pickle XSD 1.1 meta-schema: 0.0211 s
XSD 1.0 meta-schema maps copy: 0.0001 s
XSD 1.1 meta-schema maps copy: 0.0000 s
XSD 1.0 meta-schema rebuild: 0.0422 s
XSD 1.1 meta-schema rebuild: 0.0576 s
```
show that the pickle save time if the regex patterns are built in lazy mode after import (the build of XSD 1.0 meta-schema ...). Moreover after the build the meta-schema is usually reused copying the global maps, an operation that is faster and lighter in terms of memory. 

So using pickle can be useful but the impact depends by the custom needs of each user and implementing this means adding about 600K of saved meta-schema on disk for each installation. 

So I don't want to automate this at schema loading, eventually the recipe for doing this on your own is saving the meta-schema on pickle file an then loading with:

```python
import pickle
import xmlschema
with open("meta1.0.pickle", mode='rb') as fp:
    xmlschema.XMLSchema.meta_schema = pickle.load(fp)
```

Instead i will implement lazy regex patterns for XSD identities in order to reduce import time.

**Comment by brunato** [comment]
The same situation is for other modules that have a long import time. The impact is from compiling complex regex expressions, like XML Schema translated regex or tokenizers of base XPath parsers in elementpath or custom ones in xmlschema. All of these will be used lazy, intercepting exceptions generated when you try to create an instance of not built parser class.

**Comment by brunato** [comment]
In the new version v1.3.0 the import time should be almost halfed avoinding the build of XPath tokenizers. I think this is not easily further reduceable. In some module that take longer, like schemas.py, the time is spent to build schema classes and i did't found another points of overhead in the code.

Automatic loading of serialized meta-schema will not be implemented. I don't want to introduce a mechanism by default, and another solution would requires a deep revision of XMLSchema class build and of its metaclass.

Best regards
