### ISSUE TITLE
ColumnConverter with xs:union

### ISSUE THREAD

**Issue by davlee1972** [sissaschool/xmlschema#209]
PyArrow 2.0 got released recently with support for nested data structures.

The only failure I ran into so far is with <xs:union memberTypes="xs:double xs:string"/> since a column can't be both a double and a string. I'll see if I can fix the ColumnConverter class in converters.py

Long term it would be cool if we could go directly from XML to Arrow.

https://docs.microsoft.com/en-us/dotnet/standard/linq/sample-xsd-file-customers-orders
https://docs.microsoft.com/en-us/dotnet/standard/linq/sample-xml-file-customers-orders

```
/* Read JSON generated from XML using ColumnConverter into Arrow Memory and then save to Parquet */
import pyarrow.json as js
import pyarrow.parquet as pq

arrow_data = js.read_json("CustomerOrders.json")
pq.write_table(arrow_data, "CustomerOrders.parquet")

arrow_data.schema
```

```
Root: struct<Customers: struct<Customer: list<item: struct<CustomerCustomerID: string, CompanyName: string, ContactName: string, ContactTitle: string, Phone: string, FullAddress: struct<Address: string, City: string, Region: string, PostalCode: string, Country: string>, Fax: string>>>, Orders: struct<Order: list<item: struct<CustomerID: string, EmployeeID: string, OrderDate: timestamp[s], RequiredDate: timestamp[s], ShipInfo: struct<ShipInfoShippedDate: timestamp[s], ShipVia: int64, Freight: double, ShipName: string, ShipAddress: string, ShipCity: string, ShipRegion: string, ShipPostalCode: string, ShipCountry: string>>>>>
  child 0, Customers: struct<Customer: list<item: struct<CustomerCustomerID: string, CompanyName: string, ContactName: string, ContactTitle: string, Phone: string, FullAddress: struct<Address: string, City: string, Region: string, PostalCode: string, Country: string>, Fax: string>>>
      child 0, Customer: list<item: struct<CustomerCustomerID: string, CompanyName: string, ContactName: string, ContactTitle: string, Phone: string, FullAddress: struct<Address: string, City: string, Region: string, PostalCode: string, Country: string>, Fax: string>>
          child 0, item: struct<CustomerCustomerID: string, CompanyName: string, ContactName: string, ContactTitle: string, Phone: string, FullAddress: struct<Address: string, City: string, Region: string, PostalCode: string, Country: string>, Fax: string>
              child 0, CustomerCustomerID: string
              child 1, CompanyName: string
              child 2, ContactName: string
              child 3, ContactTitle: string
              child 4, Phone: string
              child 5, FullAddress: struct<Address: string, City: string, Region: string, PostalCode: string, Country: string>
                  child 0, Address: string
                  child 1, City: string
                  child 2, Region: string
                  child 3, PostalCode: string
                  child 4, Country: string
              child 6, Fax: string
  child 1, Orders: struct<Order: list<item: struct<CustomerID: string, EmployeeID: string, OrderDate: timestamp[s], RequiredDate: timestamp[s], ShipInfo: struct<ShipInfoShippedDate: timestamp[s], ShipVia: int64, Freight: double, ShipName: string, ShipAddress: string, ShipCity: string, ShipRegion: string, ShipPostalCode: string, ShipCountry: string>>>>
      child 0, Order: list<item: struct<CustomerID: string, EmployeeID: string, OrderDate: timestamp[s], RequiredDate: timestamp[s], ShipInfo: struct<ShipInfoShippedDate: timestamp[s], ShipVia: int64, Freight: double, ShipName: string, ShipAddress: string, ShipCity: string, ShipRegion: string, ShipPostalCode: string, ShipCountry: string>>>
          child 0, item: struct<CustomerID: string, EmployeeID: string, OrderDate: timestamp[s], RequiredDate: timestamp[s], ShipInfo: struct<ShipInfoShippedDate: timestamp[s], ShipVia: int64, Freight: double, ShipName: string, ShipAddress: string, ShipCity: string, ShipRegion: string, ShipPostalCode: string, ShipCountry: string>>
              child 0, CustomerID: string
              child 1, EmployeeID: string
              child 2, OrderDate: timestamp[s]
              child 3, RequiredDate: timestamp[s]
              child 4, ShipInfo: struct<ShipInfoShippedDate: timestamp[s], ShipVia: int64, Freight: double, ShipName: string, ShipAddress: string, ShipCity: string, ShipRegion: string, ShipPostalCode: string, ShipCountry: string>
                  child 0, ShipInfoShippedDate: timestamp[s]
                  child 1, ShipVia: int64
                  child 2, Freight: double
                  child 3, ShipName: string
                  child 4, ShipAddress: string
                  child 5, ShipCity: string
                  child 6, ShipRegion: string
                  child 7, ShipPostalCode: string
                  child 8, ShipCountry: string
```

**Comment by brunato** [comment]
Hi,
checking multiple data coherence in converters could be very hard, because they act mainly as data shapers with a point of view focused on current element. 

It maybe better to think about another optional mechanism (similar to xsi:type) that can be pushed inside iter_decode methods to fix a xs:union to a specific type for the entire decode run. Feel free to propose a PR for this.

About the directly XML to Arrow converter i think that should be useful in particular if there is a manner to write with a lazy encoder, like i do for JSON, for decoding big XML files.

In any case I would avoid to add other dependencies to xmlschema, so this can be the theme for a dependant package. In the last release I've removed import of lxml, limiting to a programmatic import of lxml if requested for element serialization.  But I don't think that can be done similarly for pyarrow objects, so a dependant package should be a better choice.

**Comment by brunato** [comment]
A further option would be to add _pyarrow_ as an optional dependency in a subpackage or inside related API functions (maybe better with a subpackage for separation and clarity ...). Lxml is not really a dependency because the import is done when you already provide an lxml's element to an xmlschema API (in fact this happens only inside etree_tostring()).

But with _pyarrow_ this has to be managed with setuptools's **extras_require** option. Furthermore extending a library with other optional features may have sense if the develop of these sections has the support of whom is involved on the specific topic, in order to fix issues and provide tests.

**Comment by brunato** [comment]
Hi @davlee1972,
in v1.5 I've added a separated subpackage (xmlschema.extras for hosting optional contributions, particularly suited for parts that require extra dependencies). If your request is still valid you can think to contribute with extra API to put in a module `xmlschema.extras.arrow`.
