### ISSUE TITLE
XML read issue with CCSDS Nav Data Msg files

### ISSUE THREAD

**Issue by egemenimre** [sissaschool/xmlschema#212]
I'm trying to read an XML file given in the CCSDS Standard [given here](https://cwe.ccsds.org/moims/docs/MOIMS-NAV/Test-Messages/XML/elementFormDefaultUnqualified/cdm-example-section4-R1.6.xml).

I'm getting the following error:
```
xmlschema.validators.exceptions.XMLSchemaChildrenValidationError: failed validating <Element 'cdm' at 0x7fb3a15f4590> with XsdGroup(model='sequence', occurs=[1, 1]):

Reason: Unexpected child with tag 'header' at position 1. Tag ndm:header expected.
```
I'm a bit of a newbie in handling XML files, so I have no idea what is going on. But the XSD files are defined in the standard and so is the example file, so I don't think there is  an issue with them. 

For reference, the XSD files can be found [here](https://github.com/egemenimre/ccsds-ndm/tree/main/xsd_files/ndmxml-1.0.C-schemas-qualified). And you can find a simple source code to generate the error [here](https://github.com/egemenimre/ccsds-ndm/issues/2#issue-743216466).

**Comment by brunato** [comment]
Hi,
essentially the sample XML file is invalid. 

The root element 'cdm' has no namespace (as clearly declared in `ndmxml-1.0-master.xsd`) but its children, and so also 'header' child, should be in the namespace "urn:ccsds:recommendation:navigation:schema:ndmxml" (ndm is the associated prefix so _xmlschema_ report the mapped name ndm:header as the expected tag).

This error is confirmed also by other validators (Xerces, lxml). This is my test with lxml:
```pycon
>>> import lxml.etree as et
>>> xs = et.parse("ndmxml-1.0-master.xsd")
>>> schema = et.XMLSchema(xs.getroot())
>>> xt = et.parse("../../cdm_example_section4.xml")
>>> schema.validate(xt.getroot())
False
>>> schema.error_log
../../cdm_example_section4.xml:6:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'header': This element is not expected. Expected is ( {urn:ccsds:recommendation:navigation:schema:ndmxml}header ).
```

I don't know why the sample file in the standard blue book is wrong, maybe it could depends on the XML writer tool used when it was authored.

I unsuccessfully tried to search another sample file. Better if you try to find other samples. Otherwise rewrite your XML sample mapping all the elements to the right namespace (using the namespace declaration `xmlns:ndm="urn:ccsds:recommendation:navigation:schema:ndmxml"`), except the ones declared in `ndmxml-1.0-master.xsd`.

**Comment by egemenimre** [comment]
Oh dear, to find an erroneous XML in the standard itself is a bit depressing.

Could you please have a quick look [here](https://cwe.ccsds.org/moims/docs/Forms/AllItems.aspx?RootFolder=%2Fmoims%2Fdocs%2FMOIMS%2DNAV%2FDraft%20Documents%2FNavigation%20Data%20Messages%2DXML%20Specification%20%28NDM%2DXML%29%2FNDM%2DXML%2DTestFiles&FolderCTID=0x012000C8EEDFBFAD59894AB84FF1AF9485D0AB&View=%7B72CC1C3E%2DEFA9%2D498B%2DBEA5%2DC88E7DEE0C54%7D), there is a bunch of XML files used in the standard documents (ODM, OEM, CDM etc.). I couldn't get any of them to work. I suspect the namespace issue is common to all of them, so we will have to find other examples.

**Comment by brunato** [comment]
> Could you please have a quick look [here](https://cwe.ccsds.org/moims/docs/Forms/AllItems.aspx?RootFolder=%2Fmoims%2Fdocs%2FMOIMS%2DNAV%2FDraft%20Documents%2FNavigation%20Data%20Messages%2DXML%20Specification%20%28NDM%2DXML%29%2FNDM%2DXML%2DTestFiles&FolderCTID=0x012000C8EEDFBFAD59894AB84FF1AF9485D0AB&View=%7B72CC1C3E%2DEFA9%2D498B%2DBEA5%2DC88E7DEE0C54%7D), there is a bunch of XML files used in the standard documents (ODM, OEM, CDM etc.). I couldn't get any of them to work.

I see in the link other more recent versions of the standard (1D and 2). Both of them have the same *"problem"* of master XSD with global elements in no namespace and internal ones in a namespace. This choice is quite unusual. 

My suggestion is to try to contact a member of the working group that maintain the schemas and ask about this choice and which XML tools they use for processing schemas and data. The xml samples are invalid anyway but having more information can help you to understand the reason of this choice.

**Comment by egemenimre** [comment]
Thanks for looking into that, I guess talking to the folks and notifying them seems to be the only choice.

So far, I have tried `xmlschema` and `xmldict` to read the file (the latter was surprisingly successful). And I tried `xsdata` to auto-generate parser classes from the xsd files, but unsurprisingly, the generated parsers can't read the XMLs.

I will close the issue, as this is not an `xmlschema` problem as such. That said, I will post their reply here for your info.

**Comment by egemenimre** [comment]
OK, just to follow up, I contacted the CCSDS Nav Group regarding the issue and they responded very promptly. They advised me to make sure I sure the xsd files at SANA Registry: https://sanaregistry.org/r/ndmxml 

I have managed to get all xmlschema and xsdata to play along nicely. You can see the result here: https://github.com/egemenimre/ccsds-ndm 
- `xsd_files/ndmxsd` directory has the active xsd files that I use for xmlschema
- `src/examples/xmlschema_example.py` shows the example that reads the sample file.

That said, I am none the wiser as to why that works now. Maybe the namespaces were eventually fixed in the published ones in SANA?

Nevertheless, thank you for your help!

**Comment by brunato** [comment]
Hi,
the difference with the previous schemas is the "unqualified" default form for elements, that means that all non-global (internal) elements are accepted also with the unqualified (local name) form. I was wrong before about XML sample files: they are valid against an unqualified version of schemas, because the global elements are only the ones defined in *master* xsd file, and they do not belong to any namespace. The other elements (eg. `<header>`) are all internal, so they can appear also in unqualified form.

The mapping into "urn:ccsds:recommendation:navigation:schema:ndmxml" , is implicit by the definition of external global elements that are in no namespace. This choice is a bit unusual (i would prefer to put also the global elements in the same namespace, and then use `xmlns="urn:ccsds:recommendation:navigation:schema:ndmxml"`) but it's perfectly admitted in XML Schema. Probably it was choosen in order to have all the elements's tags in local form.
