### ISSUE TITLE
Convert xs:date to a python datetime type

### ISSUE THREAD

**Issue by mblahay** [sissaschool/xmlschema#229]
How might one create a converter that can produce datetime types from xs:date?

**Comment by brunato** [comment]
Datatypes are managed by simpleTypes's decoders, not by converters, anyway (using `datetime_types=True` when call decoding) the converter instance could re-decode Date10/Date values to a datetime, but this can be a bit complicated and it's a misusage of converter instances that are intendeded to act at XML element level and on shape of decoded data.

Maybe this could be better handled with an enhancement at schema creation with a rebuild of base decoders, replacing xsd builtin decoder ('to_python' attribute in builtin types) with a custom one.

**Comment by mblahay** [comment]
Is this the piece of code you are referring to?    

{
        'name': XSD_DATE,
        'python_type': (datatypes.Date10, str),
        'admitted_facets': DATETIME_FACETS,
        'facets': [COLLAPSE_WHITE_SPACE_ELEMENT],
        'to_python': datatypes.Date10.fromstring,
    },  # [-][Y*]YYYY-MM-DD

What about python_type? Why is it a tuple here?

**Comment by brunato** [comment]
Exactly, but replacing this is not trivial, because a change of `xsd_builtin_types_factory()` is required or otherwise add a method for replacing the decoder of an instance to `XsdAtomicBuiltin` class.

_python_type_ is a tuple because for default date/datetime values are decoded to strings. The tuple can be used by type checking with `isinstance()` in the same way as a single class. The 1st type of this tuple is the reference type (used for decoding when to_python is not provided. You can found more info in doc and init of `class XsdAtomicBuiltin`.

**Comment by mblahay** [comment]
I see what you mean about the change being non-trivial. I have opted to leave it as is and will instead simply walk the resulting python structure and convert the date types as needed. Thanks for your help.

**Comment by brunato** [comment]
Hi,
maybe you have already solved your problem but I want to inform you that in the release v1.6.0 I added an option _'value_hook'_ to decoding methods. With this option a function can be provided to apply a custom decode to simple values after validation. Check documentation for details.

**Comment by mblahay** [comment]
Thank you, I will definitely take a look at this.
