### ISSUE TITLE
Validation algorithm

### ISSUE THREAD

**Issue by handsomeyang** [sissaschool/xmlschema#231]
Thanks for the great library. I am just wondering if there is documentation on the schema validation algorithm implemented. Thanks.

**Comment by brunato** [comment]
Thank you for the appreciation for this work. I'm sorry but there is no formal documentation yet on validation algorithm.

I've build validation upon a set of generators functions and then adding specific parts for validating content model (_ModelVisitor_ that validates model groups with a stack, using the principles defined in XSD 1.0/1.1 standards), where using generators where too complex.

The idea of generators was taken from a [similar package written for JSON data](https://github.com/Julian/jsonschema), when I saw a presentation of it by the author, at PyCon IT in Florence. 

Using Python generators are handful because reduce the need of putting values into lists, an produce flows of data or errors, that can be used as needed, with flexibility. For instance it let be simple managing validation without duplicating code. Furthermore generators stores status inside and let you propagate an error and then continue (if validation mode is 'lax').

On decoding the idea of converters emerged when a user ask me about the need of shaping data in different manners.
