### ISSUE TITLE
Modify a schema

### ISSUE THREAD

**Issue by handsomeyang** [sissaschool/xmlschema#232]
Hi,

Just wondering if there is a way to modify a XML schema using the library's APIs. For example, can I add an XsdAttribute to a XsdComplexType? Thanks.

**Comment by brunato** [comment]
Hi,
adding schema components is possible but discouraged, because they need to add a reference declaration/definition to XSD source. Also for instance you can add an attribute to a _complexType_ but if this type is a restriction and the attribute that you add is not in the set of base attribute the schema should be invalid.

So the proper way is to edit a copy of your XSD fileset and add the components that you need or better is to create a redefinition/overriding schema for the namespace, extending or restricting components as you need, and rebuild the complete schema starting from this. The last is the standard approach of modifying existing public XSD schemas.

Best regards

**Comment by handsomeyang** [comment]
Thanks for the reply. I reckon that programmatically modifying a schema could be a potential use case in some situations. Are you aware of any libraries that can facilitate that

**Comment by brunato** [comment]
I agree but making this is not a simple task and naive implementations can generate more problems than editing a redefinition/overriding schema. I don't know any Python library that accomplish this need, maybe it could exists in other languages (Java).

**Comment by handsomeyang** [comment]
Thanks
