### ISSUE TITLE
Code generator and converter

### ISSUE THREAD

**Issue by handsomeyang** [sissaschool/xmlschema#233]
Hi,

What is the difference between the code generator and the converter
Can code generator be used to generate XML document instances from a XML schema, if so, how to do that

Thanks

**Comment by brunato** [comment]
Hi,
code generators are intended for building code interfaces for representing XML documents. I tried to create generators classes that include helpers (custom jinja2 filters/tests) for writing jinja2 templates based on XSD schemas.

Converters are usually intended for decoding/encoding raw data (eg. to/from JSON). Anyway in the last releases I've added converters for creating high level objects (eg. `DataElementConverter` and `DataBindingConverter`), with `DataElement` class as the base.

The border between code generators and high-level converters is not so sharp because DataElement objects (also XML data bindings classes) can be generated statically with a template (take a look at _bindings.py.jinja_).
