### ISSUE TITLE
myschema.validate () does not accept a byte string as input.

### ISSUE THREAD

**Issue by piscvau** [sissaschool/xmlschema#238]
In ressources.py line 174 raises a builtin.TypeError "a bytes-like object is required, not 'str" whenever obj is a byteString

**Comment by brunato** [comment]
Hi,
bytes strings are still not supported. Maybe this can be labeled as an enhancement.

**Comment by piscvau** [comment]
Hello 
in line 172 of ressources.py it seems that obj can be a bytestring. 
if not isinstance(obj, (str, bytes))....

This is why I reported what I thought was an issue!....

**Comment by brunato** [comment]
You are right. Maybe it was a tentative of making this compatible.

But making this compatible with bytes-strings is not possible without complicating low level operations on strings. So I think that the only feasible choice is to decode bytes-strings to Unicode strings.

**Comment by brunato** [comment]
Seems to be simpler than I thought because it is almost all handled by ElementTree library (as already happen when a remote XML resource is downloaded using urlopen). Only small modifications in XMLResource class were needed to let it work.

So the acceptance of bytes XML sources will be included in next release.

**Comment by brunato** [comment]
Hi,
the release v1.6.1 supports also bytes strings, 
thank you for reporting this
