### ISSUE TITLE
Problems with importing .xsd

### ISSUE THREAD

**Issue by luminita** [sissaschool/xmlschema#239]
Hi

I am trying to load an XML schema. The .xsd file imports some other xsd files, which as far I understand from the documentation should be supported. However, although I have tried to change the paths in all possible ways, I am still getting the error:

Traceback (most recent call last):
  File "/Users/lumifarn/work/pycharm-workspaces/tests/venv/lib/python3.8/site-packages/xmlschema/validators/global_maps.py", line 131, in lookup
    obj = global_map[qname]
KeyError: '{http://www.pubtrans.com/PT/1.0}Messages'

I am attaching both my code, as well as the xsd files.

Thanks 
Luminita

[xmlschema_error.zip](https://github.com/sissaschool/xmlschema/files/6287611/xmlschema_error.zip)

**Comment by brunato** [comment]
Hi,
i checked the schemas and they are not conforming to the standard. Imports of namespaces are done once, until a successful source is found and loaded.

In detail the file `ROI-FromPubTrans.xsd` contains two imports of namespace "http://www.pubtrans.com/PT/1.0":

```XML
        <xs:import namespace="http://www.pubtrans.com/PT/1.0" schemaLocation="./PTShared/PT-SharedTypes.xsd"/>
        <!--== Uses XMLStream based trasport mechanism == -->
        <xs:import namespace="http://www.pubtrans.com/PT/1.0" schemaLocation="./PTShared/PT-XMLStream.xsd"/>
```
but conformant XSD validators load only the 1nd XSD file, and the 2nd is ignored because the namespace is already loaded.

If in some contexts both files are required an _xs:include_ statement has to be added to one of them (maybe PTShared/PT-XMLStream.xsd). Also reciprocal xs:imports can be added (_xs:include_ considers the resource URL as stop criteria so there are no loading loops).

Without modifying the schemas you can load and build the schema with these statements:

```pycon
>>> import xmlschema
>>> schema = xmlschema.XMLSchema('ROI-FromPubTrans.xsd', build=False)
>>> schema.import_schema("http://www.pubtrans.com/PT/1.0", "PTShared/PT-XMLStream.xsd", force=True)
XMLSchema10(name='PT-XMLStream.xsd', namespace='http://www.pubtrans.com/PT/1.0')
>>> schema.build()
```
but this is a non-standard loading and schemas could be consider invalid by other XSD validators.

Best regards
Davide

**Comment by luminita** [comment]
Thank you very much Davide, it works now when using your code.
