### ISSUE TITLE
Support additional xml parser

### ISSUE THREAD

**Issue by fkromer** [sissaschool/xmlschema#290]
It seems like xmlschema supports Python's ElementTree XML library for parsing only. It would be great if one could use other parsers like e.g. lxml instead.

**Comment by brunato** [comment]
Hi,

the problem of supporting both ElementTree and lxml.etree is about managing vulnerabilities to XML based attacks (see the documentation for [defusedxml](https://pypi.org/project/defusedxml/) on PyPI). Also _lxml_ support in _defusedxml_ is deprecated:

```pycon
>>> import defusedxml.lxml
<stdin>:1: DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.
```


Also managing lazy mode is different and more complicated to handle, because _lxml_ includes parent linkage on tree elements.

For these reasons the _lxml_ support is and will be limited to providing already parsed _lxml_ trees to _xmlschema_.
