### ISSUE TITLE
use of XMLschema to build schema instances from python classes

### ISSUE THREAD

**Issue by piscvau** [sissaschool/xmlschema#296]
Please excuse me if this is a trivial question but I am not an XMLSchema expert nor a python expert. I am developing an open source software for knitting. My purpose is to distribute knitting models from a community platform and provide an open source software to interpret these models and assist users of old knitting machines from the 1980's!....I have manually written some XMLSchemas but I would like to enhance the process. 

I would like to use the library to create XMLSchemas from python classes , especially Django model classes. I imagine adding  methods to each model class, starting from fields,  to define how to map it to a  XML type. Then I would use the export method to create the schema file.

After thorough study of the documentation, I do not see how to use the library to do this. I understand I need to create Schema Classes and  I suspect that I need to create DataElement and "assemble them" to create a Schema instance. 
The documentation is very detailed about how to use the library to inspect schemas after they are parsed  but I do not see any hint or example on how to create Schemas instances. In particuler the parameter nsmap, xsd_element association are not clear to me.

Again please excuse me if this is a trivial question.

**Comment by brunato** [comment]
Hi,
I'm sorry but the library works only using existing XSD sources.

DataElement is a Python representation of an XML element, that is usually related to an *xs:element* of a schema. If not the DataElement uses the default decoder/encoder provided by XSD meta-schema (always valid, string values).

Evolutions of this basic idea could be developed in the future, but i've no plan for this. Maybe it could be a specialized code generator based on Jinja2 templates (see `extras/` subpackage).

**Comment by piscvau** [comment]
Thanks for your quick reply.
 I am going to use the E Factory from lxml to build the schemas.
To build instances from python classes, would you suggest to use the DataElement class or nested dictionnaries and the encode method.*?
I thank you again from your help.

**Comment by brunato** [comment]
> To build instances from python classes, would you suggest to use the DataElement class or nested dictionnaries and the encode method.*?

Depends if you need  raw data (json from XML) or high-level objects. 

Furthermore, DataElement is also the base for building customized XML data binding objects using jinja2 templates.
Take a look at `xmlschema.extras.codegen.PythonGenerator` and `xmlschema/extras/templates/python/bindings.py.jinja`.

Cheers

**Comment by piscvau** [comment]
Hello Thanks again for your quick response. I definitely need more of high_level objects than raw data.
 I have looked into the extras and the jinja2 templates. but I do not get the full picture, even fuzzy!....I will spend more time on it tomorrow.
I also kind of suspect that if I use Jinja2 templates to create the XML instances from my classes, I could just as well use it (different templates ) to create the Schemas. However for a non Python expert it seems like a mountain to climb and I miss ideas about where to start climbing!...
Thanks again for your help I really appreciate it!... .

**Comment by piscvau** [comment]
Hello
 If I may ask another question question : files  xmlschema/extras/templates/python/bindings.py.jinja and sample.py.jinja are auto generated files using the codegen.PythonGenerator? 
Could you point to the code that produced this files as output, using the PythonGenerator.
Again sorry if this is a trivial question.

**Comment by piscvau** [comment]
I think the documentation mentions a smal package extras/testing but I do not see it. Did I miss it?
Thanks again for your help.

**Comment by brunato** [comment]
> Hello If I may ask another question question : files xmlschema/extras/templates/python/bindings.py.jinja and sample.py.jinja are auto generated files using the codegen.PythonGenerator? Could you point to the code that produced this files as output, using the PythonGenerator. Again sorry if this is a trivial question.

Not exactly, these .jinja files are sample default templates templates that a PythonGenerator instance can use to create auto-generated Python modules. See tests (`tests/test_codegen.py`) for examples of usage.

Jinja2 template system is a powerful template library, often used also for code generation. Making other templates you can extend the complexity of Python generated code, making also custom method inside generated classes/functions. 

Initially code generators were not intended to be included in *xmlschema*. They were developed for a specific case of creating XSD based interface for a scientific Fortran suite (called Quantum ESPRESSO), but someone asked to have this feature inside so I had included here as _extras_ (because it requires an additional dependency).

**Comment by brunato** [comment]
Hi,
in the version v1.11.0 I have included translations for parsing/validation error messages. 
For activating the translation you can use:

    import xmlschema
    xmlschema.translation.activate()   # or xmlschema.translation.activate(languages=['ru'])

Translation can be also deactivated:

    xmlschema.translation.deactivate()

Translations are not installed in builtins for default (provide `activate(install=True)`).

At schema level I've removed the proposed options because currently are not manageable at instance level with coherence.

I have built a new xmlschema.POT template, that can be considered completed (I don't want to extend it to error
messages not related with validation/parsing).

The version v1.11.0 includes a full italian translation and a partial Russian translation derived from your PR. Complete 
with a full russian translation with another PR and then i will publish a new release.

**Comment by piscvau** [comment]
No problem. In fact the comment helped me. My problem was a misinterpretation of your sample.py.jinja and bindings.py.jinja files. Because they include a comment saying they are "auto-generated files", I desperately was looking for the jinja2 templates that generated these 2 files!.... It was clearly a misunderstanding of the comment. looking at tests/test_codegen.py clarified it!.....

**Comment by piscvau** [comment]
However I still do not understand how to encode data from a manually written python class (already existing) into an XML file based on an existing schema instance. The usage documentation says that you can encode an object which has been decoded but I have deeply looked into the documentation and did not see any hint about how to create from scratch sucn an object.  I did look also into the bindings.py.jinja. but this seems more appropriate to decode an xml element using the schema than to encode it.

I have no experience in creating nor using data bindings so any hint or example you could provide would be highly appreciated. 
I thank you in advance.

**Comment by piscvau** [comment]
keeping digging into the documentation I notice that the schema.iter_encode method does not say anything about the dataobject required as first positional argument. Does this mean this method is really intened to encode a data object that was decoded by the package. If not where to find out information about which type of object is required, which structure ?
