### ISSUE TITLE
Iterate over schema / generate valid xml file(structure) without data?

### ISSUE THREAD

**Issue by zdposter** [sissaschool/xmlschema#371]
Is there way how to iterate over over schema elements?

I try to create xml header based on schema without need to specify everything manually. 
I saw some suggestion to use empty json object as input data, but there is XMLSchemaChildrenValidationError because of incomplete content of elements....

```py
import xmlschema
import json

schema = xmlschema.XMLSchema("https://ekr.financnasprava.sk/Formulare/XSD/svdph20.xsd")
data = json.dumps({})               
xml = xmlschema.from_json(data, schema=schema, preserve_root=True)
```

**Comment by brunato** [comment]
Hi,

your schema is relatively simple (has no imports/includes, only one root element). With only one root element the encoding from an empty json can produce an empty root element (_dokument_), otherwise you have to provide a choice through the `path` argument.

Anyway for avoiding error raises (the schema root cannot be empty in your case) you have to provide a not 'strict' validation argument, e.g.:

```python
 xml, errors = xmlschema.from_json(data, schema=schema, validation='lax')
```

or

```python
xml = xmlschema.from_json(data, schema=schema, validation='skip')
```

For iterating over schema elements the recipe is:

```pycon
>>> import xmlschema
>>> 
>>> schema = xmlschema.XMLSchema("https://ekr.financnasprava.sk/Formulare/XSD/svdph20.xsd")
>>> all_elements = list(schema.iter_components(xsd_classes=xmlschema.XsdElement))
```

This includes _all elements_ defined in the same namespace (in your case there is only one schema, but cases with 'xs:includes' require a built or more schema instances connected together using a global map instance).

If you need only the global elements you can access `schema.elements` dictionary or use `schema.iter_globals()` API (see the documentation for using this).

**Comment by zdposter** [comment]
```
data = json.dumps({})  
xml, errors = xmlschema.from_json(data, schema=schema, validation='lax')
```
just creates:
```
<?xml version='1.0' encoding='utf8'?>\n<dokument />
```

`all_elements = list(schema.iter_components(xsd_classes=xmlschema.XsdElement))`  produces list of elements but without hierarchy.

I am looking for something that creates empty&valid xml:
```
<?xml version='1.0' encoding='utf-8'?>
<dokument>
 <hlavicka>
  <identifikacneCislo>
   <kodStatu/>
   <dic/>
  </identifikacneCislo>
  <danovyUrad/>
  <druhSV>
   <riadny/>
   <opravny/>
   <dodatocny/>
  </druhSV>
  <obdobie>
   <mesiac/>
   <stvrtrok/>
   <rok/>
  </obdobie>
  <obchodneMeno>
   <riadok/>
   <riadok/>
   <riadok/>
   <riadok/>
  </obchodneMeno>
  <adresa>
   <ulica/>
   <cislo/>
   <psc/>
   <obec/>
   <tel/>
   <email/>
  </adresa>
  <celkovaHodnota/>
  <konatel/>
  <konatelTel/>
  <konatelEmail/>
  <datumVyhlasenia>
   <den/>
   <mesiac/>
   <rok/>
  </datumVyhlasenia>
 </hlavicka>
 <telo>
  <strana>
   <zaznam>
    <kodStatu/>
    <idCislo/>
    <hodnota/>
    <kod/>
   </zaznam>
...
   <zaznamCast2>
    <kodStatu/>
    <idCislo/>
    <idCislo2/>
    <vratenieTovaru/>
    <oprava/>
   </zaznamCast2>
  </strana>
 </telo>
```

**Comment by brunato** [comment]
Ok, you intended a not empty document with empty simple content elements, right?

**Comment by brunato** [comment]
Anyway this library does not support XML generation from a `XMLSchema` instance, nor it will. This could be the target of another package that uses _xmlschema_ and its API for parsing XSD files.

**Comment by zdposter** [comment]
Thank you very much for explanation.
