### ISSUE TITLE
different validations on different element levels

### ISSUE THREAD

**Issue by MandolinMicke** [sissaschool/xmlschema#383]
Hi
Thanks for a create project. 

I have one issue since the latest major release though that I can't fully understand. 
I use this project for my own package where I have a number of classes responsible for a small part of a complete xml and I use this package to test each class output to the xsd schema. 

I basically do this:

```
validator = schema.create_element("Test", type=top_element_name)
validator.validate(element_to_test)
```

However since the latest release of xmlschema I have a really strange issue. 

The full xml looks like this:
```
<road rule="RHT" id="0" junction="-1" length="100">
    <link/>
    <planView>
        <geometry s="0" x="0" y="0" hdg="0" length="100">
            <line/>
        </geometry>
    </planView>
    <elevationProfile/>
    <lateralProfile/>
    <lanes>
        <laneSection s="0">
            <left>
                <lane id="1" type="driving" level="false">
                    <link/>
                    <width a="3.0" b="0.0" c="-0.0" d="0.0" sOffset="0"/>
                    <roadMark sOffset="0" type="solid" weight="standard" color="standard" height="0.02" width="0.2"/>
                </lane>
            </left>
            <center>
                <lane id="0" type="none" level="false">
                    <roadMark sOffset="0" type="solid" weight="standard" color="standard" height="0.02" width="0.2"/>
                </lane>
            </center>
            <right>
                <lane id="-1" type="driving" level="false">
                    <link/>
                    <width a="3.0" b="0.0" c="-0.0" d="0.0" sOffset="0"/>
                    <roadMark sOffset="0" type="solid" weight="standard" color="standard" height="0.02" width="0.2"/>
                </lane>
            </right>
        </laneSection>
    </lanes>
    <objects>
        <object id="1" s="10.0" t="-2" subtype="None" dynamic="no" zOffset="0.0" pitch="0" roll="0" height="1.0" type="pole" orientation="+" hdg="0"/>
        <object id="2" s="20.0" t="-2" subtype="None" dynamic="no" zOffset="0.0" pitch="0" roll="0" height="10" type="streetLamp" orientation="+" hdg="0">
            <outlines>
                <outline>
                    <cornerLocal u="1" v="2" z="3" height="4"/>
                    <cornerLocal u="1" v="2" z="3" height="5"/>
                </outline>
            </outlines>
        </object>
    </objects>
</road>
```
This fails saying that I have a missing field '@id'
```
failed validating <Element 'outline' at 0x7ff6377fcf40> with XsdElement(name='outline', occurs=[1, None]):
Reason: missing key field '@id' for XsdKey(name='k_road_objects_object_outlineId')
```
However if I only test the sub element object or outlines

so this:
  ```
<object id="2" s="20.0" t="-2" subtype="None" dynamic="no" zOffset="0.0" pitch="0" roll="0" height="10" type="streetLamp" orientation="+" hdg="0">
    <outlines>
        <outline>
            <cornerLocal u="1" v="2" z="3" height="4"/>
            <cornerLocal u="1" v="2" z="3" height="5"/>
        </outline>
    </outlines>
</object>
```
or 
```
 <outlines>
    <outline>
        <cornerLocal u="1" v="2" z="3" height="4"/>
        <cornerLocal u="1" v="2" z="3" height="5"/>
    </outline>
</outlines>
```
It passes the validation checks. 

the scemas can be found here:[opendrive_17_.zip](https://github.com/sissaschool/xmlschema/files/13887101/opendrive_17_.zip)

**Comment by brunato** [comment]
Hi,
thank you for the detailed explanation of the issue, but i don't understand how the schema has been built (from which file included in the zipfile) and which is the value of _top_element_name_:

```
validator = schema.create_element("Test", type=top_element_name)
validator.validate(element_to_test)
```

With v.3.0 the processing of namespaces is changed, centering all in the mapper/converter objects, so maybe something can be different in the direct validation from components (and maybe something have to be fixed with a supplementar setup of validation args).

thank you

**Comment by brunato** [comment]
The different behavior is related with commit 43657b267f56f8a2929911e6ab0ccccb573e90fd. In v3.0.0 the *'source'* argument is added to the keyword arguments of validation process and so the identity keys are still collected and validated.

I'll examine if adding a different criteria for excluding identity keys validation (e.g. using `None` instead of a dictionary) or if it's possible a more refined processing, disabling identities that are not in the scope (hard as I remember).

**Comment by brunato** [comment]
Examining the three cases, if in the 2nd you use the type "t_road_objects_object" and in the 3rd the type "t_road_objects_object_outlines_outline", it's correct that v3.0.0 doesn't raise an error because the key constrain is defined only in a local element of type "t_road_objects".

So there is no bug for this and v3.0.0 works better than v2.5.1.

**Comment by MandolinMicke** [comment]
Hmm ok. Then I have too look into how to fix that in the xml. 

Thanks for the help!

**Comment by brunato** [comment]
> Hmm ok. Then I have too look into how to fix that in the xml.
> 
> Thanks for the help!

Instead of creating dummy elements use the `find` API on schema object to retrieve the local elements.
Bye
