### ISSUE TITLE
Filling a schema to create a new xml

### ISSUE THREAD

**Issue by MathMan112** [sissaschool/xmlschema#400]
I need a way of creating xml documents out of .xsd schemas. Is this possible using xmlschema, and if so how.

Below is a simple example "test.xsd" that xmlschema fails to fill.

```
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://address0.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ser="http://address0.com" xmlns:ds="http://www.address1.com">
    <xs:import namespace="http://www.address2.com" schemaLocation="xmldsig-core-schema.xsd"/>
    <xs:complexType name="class">
        <xs:sequence>
            <xs:element name="student1" type="ser:String32" minOccurs="0" maxOccurs="1"/>
            <xs:element name="student2" type="ser:String32" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="class" type="ser:class"/>
    <xs:simpleType name="String32">
        <xs:restriction base="xs:normalizedString">
            <xs:minLength value="1"/>
            <xs:maxLength value="32"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
```
Using the code below, I receive an error: the content of element "ser:class" is not complete.

```
import xmlschema
import json

file      = "test.xsd"
schema   = xmlschema.XMLSchema(file) 
jsondata = json.dumps({'class': {"student1": "John",  \
                                 "student2": "Rachel"}})
    
nameSpace=schema.target_namespace
xml      = xmlschema.from_json(jsondata,schema=schema,preserve_root=True,namespaces={'': nameSpace})
# write to XML
ElementTree(xml).write('myxml.xml')
```

**Comment by brunato** [comment]
Hi,

xmlschema doesn't have a feature of building XML data from schemas (or vice versa), because the generation can be very different depending on the needs of each one, and I can't afford on satisfy all the possible variations. 

So one can build its own method using the components of a built XMLSchema instance and a certain knowledge about the data that want to obtain. In your case you start from decoded data to build an XML. You don't need to dump a JSON for this, use the encode method of the schema instance, e.g.:

```python
obj = {'ser:class': {'@xmlns:ser': schema.target_namespace,
                      "student1": "John",
                     "student2": "Rachel"}}

root = schema.encode(obj, preserve_root=True)
```

The error that you receive is due to the element form of internal elements, that is declared as _unqualified_.

In fact the XML instance:

```xml
<ser:class xmlns:ser="http://address0.com">
    <ser:student1>John</ser:student1>
    <ser:student2>Rachel</ser:student2>
</ser:class>
```

is invalid against your schema, instead the instance:

```xml
<ser:class xmlns:ser="http://address0.com">
    <student1>John</ser:student1>
    <student2>Rachel</ser:student2>
</ser:class>
```
 is valid.

So, having a decoded data without namespace info:

```python
obj = {'ser:class': {"student1": "John", "student2": "Rachel"}}
```
you can encode it to an XML tree providing a namespace map for prefix 'ser'.

```python
root = schema.encode(obj, preserve_root=True, namespaces={'ser': schema.target_namespace})
```
